#!/bin/bash

#i need to copy a file from my repo into the home directroy.
#This should run insde vim-config.
cp .vimrc ~/.vimrc
# -d means directory. so If the directroy below does not exist it runs.
if [ ! -d ~/.vim/bundle/Vundle.vim]; then
	#make directory
	mkdir -p ~/.vim/bundle
	#after making the directory git clone the content to it and end the if statment.
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
#after if statment run the pluginstall this should enable the .vimrc contents
vim +PluginInstall +qall
